name = "buildtray-queue"
main = "src/worker.ts"
compatibility_date = "2023-05-30"

[[queues.producers]]
  queue = "buildtray-webhooks"
  binding = "BUILDTRAY_WEBHOOKS"

[[queues.consumers]]
  queue = "buildtray-webhooks"

[dev]
port = 8081
local_protocol = "http"
